# Generated by Django 6.0.6 on 2026-06-28 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('bloque', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='residentes.residente')),
            ],
        ),
    ]
