# Generated by Django 6.0.6 on 2026-06-28 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_vivienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('motivo', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='residentes.vivienda')),
            ],
        ),
    ]
