# Generated by Django 6.0.6 on 2026-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0003_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='documento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(default='En curso', max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
