# Generated by Django 6.0.6 on 2026-06-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0004_visita_fecha_salida_alter_visita_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('En curso', 'En curso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='En curso', max_length=20),
        ),
    ]
