# Generated by Django 6.0.6 on 2026-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0005_visita_observaciones_visita_placa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='placa',
            field=models.CharField(default='SIN-PLACA', max_length=10),
            preserve_default=False,
        ),
    ]
